Hosted happ cloning
Holo-Host/holo-nixpkgs pull request #1017
Opened 2021-12-15 13:56 UTC by robbiecarlton

2021-12-17 15:16 UTC, zo-el requested changes
one small change request

2021-12-17 15:16 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/api.js
> +      uid: isClone ? `${DEV_UID_OVERRIDE}:${happId}` : DEV_UID_OVERRIDE
I think this should be `${DEV_UID_OVERRIDE}${happId}` without the `:`, because if there is not a `DEV_UID_OVERRIDE` the uid would be `:happid` and if people want to join the same hash space it will be something that they would have to know.

2022-01-12 15:20 UTC, zo-el approved these changes
Looks good. The HHA may need to be updated with happy to include mem-proofs, But right now we are not worried about it. So it is good.

2022-03-16 10:55 UTC, peeech commented
@zo-el @robbiecarlton what's up with this PR? Are we still trying to merge it?

2022-03-16 15:55 UTC, robbiecarlton commented
> @zo-el @robbiecarlton what's up with this PR? Are we still trying to merge it?

@peeech - Yeah. Tomorrow I'm going to be cleaning up and finishing this ticket and will update and try and get this merged as part of that

2022-05-03 14:19 UTC, zo-el commented
Just merged this work into a working branch: #1245

2022-05-03 14:19 UTC, closed without merging