Infra v4: admin-portal v0.1.5
Holo-Host/holo-nixpkgs pull request #1027
Opened 2021-12-22 14:03 UTC by zo-el

2021-12-23 15:01 UTC, peeech requested changes
See comments

2021-12-23 15:01 UTC, peeech commented on overlays/holo-nixpkgs/host-console-ui/default.nix
> +      rev = "1905a33397ba0da85c24d0c3dbf92a1340df683b";
Hmm, you are pointng here to [revision](https://github.com/Holo-Host/host-console-ui/pull/35/commits/1905a33397ba0da85c24d0c3dbf92a1340df683b) that is not merged into master, nor it is passing tests. I think that both of those issues should be fixed before this PR is mergable

2022-01-10 19:03 UTC, alastairong commented on overlays/holo-nixpkgs/host-console-ui/default.nix
> +      rev = "1905a33397ba0da85c24d0c3dbf92a1340df683b";
@Holo-Host/holo-hosting has agreed to waive working agreement for this.

2022-01-10 19:03 UTC, alastairong approved these changes

2022-01-11 06:42 UTC, merged