[B-04778] verify-registration-code endpoint
Holo-Host/holo-nixpkgs pull request #1043
Opened 2022-01-13 14:29 UTC by timotree3

Changes
- Adds the endpoint
- Moves most of `index.js` into `app.js` because I was trying to make sure the server spawned in `index.js` wasn't preventing the tests from exiting. I ended up putting `--forceExit` so this change wasn't necessary, but I think it's fine to keep.
- Improve `setup-holochain.js` so it will be easier for future people to debug issues with holochain version.

2022-01-13 17:54 UTC, zo-el requested changes

2022-01-13 17:54 UTC, zo-el commented on overlays/holo-nixpkgs/membrane-proof-service/README.md
> +- `/verify-registration-code/` (PUT): Ensures that the provided registration code is associated with the provided email. (Used in quickstart)
Why is this a PUT? It should be a GET call

2022-01-13 17:54 UTC, zo-el commented on overlays/holo-nixpkgs/membrane-proof-service/src/helper/verify-code.js
> +    }
Let sync this code up with the `/register-user` endpoint. Let us make one function that both the endpoints can use to get a verified registration code, so that they stay in sync.
The function will:
- get record based on email
- validate it
- if valid return the record
- if invalid returns an error.

And then the endpoints can do what they need to with the result

2022-01-13 20:45 UTC, timotree3 commented on overlays/holo-nixpkgs/membrane-proof-service/README.md
> +- `/verify-registration-code/` (PUT): Ensures that the provided registration code is associated with the provided email. (Used in quickstart)
GET calls can't have bodies

2022-01-14 06:14 UTC, timotree3 commented on overlays/holo-nixpkgs/membrane-proof-service/src/helper/verify-code.js
> +    }
Okay, I'll do that tomorrow. One issue I foresee is that in `verifyCode`, I am distinguishing between (email found but membrane proof not found) and (email not found), but that distinction is absent in `registerUser`. I think this distinction is meaningful for the quickstart UX, so I don't want to get rid of it. Should I just add the same distinction to `registerUser`?

2022-01-14 06:30 UTC, zo-el commented on overlays/holo-nixpkgs/membrane-proof-service/README.md
> +- `/verify-registration-code/` (PUT): Ensures that the provided registration code is associated with the provided email. (Used in quickstart)
Yes, you would have to pass `params` instead of a body

2022-01-14 06:30 UTC, zo-el commented on overlays/holo-nixpkgs/membrane-proof-service/src/helper/verify-code.js
> +    }
It is useful for quickstart, so let's keep it for the `verifiyCode`, but we already have set errors types that need to be sent by the `registerUser` endpoint, So we d oo not want to add that case in `registerUser`

2022-01-17 11:50 UTC, zo-el approved these changes
Looks good

2022-01-17 19:08 UTC, merged