feat(release.nix): set releaseTools.channel name to include git rev
Holo-Host/holo-nixpkgs pull request #1205
Opened 2022-03-29 17:29 UTC by firestack

Addresses: https://github.com/Holo-Host/bugs-n-issues/issues/41

---

HoloPorts may currently fail to update properly and can get stuck when updating the channel or updating nixos. 
This PR adds git commit revision information to the releaseTools.channel invocation to rename the /nix/store path to contain the holo-nixpkgs commit id.

2022-04-06 15:30 UTC, cole-h commented on profiles/logical/current-version.nix
> +    else { text = "--failiure--"; };
```suggestion
{ lib, ... }: {
  environment.etc.holo-nixpkgs-version =
    let path = (<holo-nixpkgs> + "/.git-version"); in
    lib.optionalAttrs (builtins.pathExists path) { source = path; };
```

If `/etc/holo-nixpkgs-version` exists, it should contain a valid version -- otherwise, it should not exist, IMHO.

2022-04-08 13:17 UTC, firestack commented on release.nix
> +    gitignoreSource
Unused
```suggestion
```

2022-04-12 08:30 UTC, peeech requested changes
I have experienced an error while building on Holoport.

2022-04-12 08:30 UTC, peeech commented on profiles/logical/current-version.nix
> +    then { source = path; }
This line of code fails on HPOS with:
```
[root@hpos:~/holo-nixpkgs/profiles/logical]# nixos-rebuild test --show-trace
building Nix...
building the system configuration...
error: while evaluating the attribute 'activationScript' of the derivation 'nixos-system-hpos-21.11pre-git' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'system.activationScripts.script' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/activation/activation-script.nix:136:9:
while evaluating 'systemActivationScript' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/activation/activation-script.nix:20:33, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/activation/activation-script.nix:136:18:
while evaluating 'textClosureMap' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/strings-with-deps.nix:75:35, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/activation/activation-script.nix:49:9:
while evaluating 'id' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/trivial.nix:14:5, called from undefined position:
while evaluating the attribute 'text' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/activation/activation-script.nix:9:5:
while evaluating the attribute 'text' at undefined position:
while evaluating 'g' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/attrsets.nix:301:19, called from undefined position:
while evaluating anonymous function at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:171:72, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/attrsets.nix:304:20:
while evaluating the attribute 'value' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:585:9:
while evaluating the option `system.activationScripts.etc.text':
while evaluating the attribute 'mergedValue' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:617:5:
while evaluating the attribute 'values' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:611:9:
while evaluating the attribute 'values' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:710:7:
while evaluating anonymous function at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:597:28, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:597:17:
while evaluating definitions from `/nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/etc/etc.nix':
while evaluating 'dischargeProperties' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:669:25, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:598:137:
while evaluating the attribute 'value' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/modules.nix:452:44:
while evaluating the attribute 'buildCommand' of the derivation 'etc' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating 'concatMapStringsSep' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/strings.nix:110:5, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/etc/etc.nix:54:7:
while evaluating anonymous function at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/etc/etc.nix:54:33, called from undefined position:
while evaluating 'concatMapStringsSep' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/strings.nix:110:5, called from /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/nixos/modules/system/etc/etc.nix:54:43:
while evaluating 'escapeShellArg' at /nix/store/jwjkzi57hk43hwmfsd6p55r9s304fygp-source/lib/strings.nix:318:20, called from undefined position:
The path name '.git-version' is invalid: it is illegal to start the name with a period. Path names are alphanumeric and can include the symbols +-._?= and must not begin with a period. Note: If '.git-version' is a source file and you cannot rename it on disk, builtins.path { name = ... } can be used to give it an alternative name.
```

2022-04-12 08:30 UTC, peeech commented on profiles/logical/current-version.nix
> +    then { source = path; }
You won't see this error when building HPOS from local checkout of `holo-nixpkgs` because `.git-version` is added to the tarball in the channel. Locally it does not exist so `environment.etc.holo-nixpkgs-version` is disabled.

2022-04-12 14:57 UTC, firestack commented on profiles/logical/current-version.nix
> +    then { source = path; }
This seems to be due to a change in [github:NixOS/Nix](https://github.com/NixOS/Nix).
We're hitting [this code](https://github.com/NixOS/nix/commit/17d3ec3405eb114f89dc42d065afa887161f6149).

I've managed to build this code locally using the following 
```
# Build the source (before tarball) of the nix channel
nix-build ./release.nix -A holo-nixpkgs.src -o holo-nixpkgs
# Build the NixOS Configuration's etc directory
nix-build \
    -I holo-nixpkgs=./holo-nixpkgs \
    -I nixpkgs=./holo-nixpkgs/nixpkgs \
    -I nixpkgs-overlays=./holo-nixpkgs/overlays \
    -I nixos-config=./holo-nixpkgs/profiles/logical/holo/nightly-test-runner \
    '<nixpkgs/nixos> -A 'config.system.build.etc'
```

Using `Nix 2.6.1` I have no issues building this configuration. So I imagine this behavior has changed between older versions of `nix` and `nix 2.6.1`.

2022-04-12 19:45 UTC, peeech approved these changes
Works great!!

2022-04-12 19:45 UTC, merged