Handle duplicate domains from HHA
Holo-Host/holo-nixpkgs pull request #1273
Opened 2022-06-09 15:28 UTC by alastairong

It's possible to register the same domain to multiple happ_ids
Since domains are keys in CF's KV store, this kills the environment as cannot be populated due to duplicate keys
This is a stop-gap solution to discard all duplicate domain records so that only the first happ gets registered.

Users will be able to publish a new hApp to the same domain as long as they delete the old one.

In future, we should handle this via HHA validation that returns an error to the UI for better UX.

2022-06-09 16:36 UTC, zo-el commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +  const uniquehAppList = happList.filter((urls => ({ url }) => !urls.has(url) && urls.add(url))(new Set));
It does not return deleted entries. I have tests in HHA that cover that case.

2022-06-09 16:43 UTC, zo-el requested changes
one requested change

2022-06-09 16:43 UTC, zo-el commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
>    }
This return will let the KV store stay as is when no apps are hosted. The KV store should be updated to the empty list. So that we stop hosting whatever was paused or stopped.

2022-06-10 01:49 UTC, robbiecarlton commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +  const uniquehAppList = happList.filter((urls => ({ url }) => !urls.has(url) && urls.add(url))(new Set));
Although funnily enough, I just posted an issue that `get_my_happs` *does* return them.

2022-06-10 08:56 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
>    }
Good point! Updated - I think insertMany() works with an empty array but I haven't tested it.

2022-06-10 09:54 UTC, alastairong commented
Also taking this opportunity to bump hashspace because of too many dummy happs installed

2022-06-14 17:04 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
>      return
I thought about that. I don't think we need to clear the happ2host KV store if we're not using it but I can change it if you feel strongly.

2022-06-15 16:30 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
>      return
@zo-el ping!

2022-06-16 10:27 UTC, alastairong commented
@zo-el Please review my update. It's not as simple as removing the return. What we really are trying to do is delete every `host_for_<happ_id>` and `<happ_id>_tranches` collection that corresponds to a happ_id no longer in the host list. So I've created a new function to do that.

2022-06-22 09:32 UTC, alastairong commented
@zo-el ping for review please

2022-06-22 13:00 UTC, zo-el commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +    if (happList.some(happ_id => !collection_name.includes(happ_id))) {
@alastairong I am not sure about this condition statement.

if anyone of the happ_id is not a part of the collection_name then drop the collection?

That should cause every collection to be dropped every time right?

2022-06-22 16:26 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +    if (happList.some(happ_id => !collection_name.includes(happ_id))) {
Oh whoops!
```suggestion
    if (happList.some(happ_id => collection_name.includes(happ_id))) {
```

2022-06-22 16:31 UTC, zo-el commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +    if (happList.some(happ_id => !collection_name.includes(happ_id))) {
Even that condition will just delete/clean-up the collections that need to be updated. The Old collections(i.e. the happs that were stopped) will still remain.

Is that ok?

2022-06-22 16:36 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +    if (happList.some(happ_id => !collection_name.includes(happ_id))) {
```suggestion
    if (happList.every(happ_id => !collection_name.includes(happ_id))) {
```

2022-06-22 16:36 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +    if (happList.some(happ_id => !collection_name.includes(happ_id))) {
@zo-el Definitely wasn't ok. Head was screwed on wrong

2022-06-22 19:11 UTC, alastairong commented on overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
> +    if (happList.some(happ_id => !collection_name.includes(happ_id))) {
```suggestion
    if !happList.find( h => collection_name.includes(h)) {
```

2022-06-29 13:10 UTC, merged