Feature/new registration
Holo-Host/holo-nixpkgs pull request #1296
Opened 2022-07-19 09:05 UTC by zeeshan595

DO NOT MERGE THIS.
Please use this PR for Review my changes and the process of how everything is setup.

2022-07-20 11:10 UTC, peeech commented
- in `profiles/logical/holo/holo-business-services/default.nix` you are defining a new server. I would say it's worth creating a description (as a comment in that file?) what is the purpose of this server. That way we will be able to cross-check what services should be running on that machine. This kind of documentation will also help in a deploynmet phase.

2022-07-20 11:12 UTC, peeech commented
- it looks to me that systemd service order (defined [here](https://github.com/Holo-Host/holo-nixpkgs/pull/1296/files#diff-a4a4e24084fc6be692d82ace622e5b93509e4c84b387b93ed636c2c555d67398R32) and [here](https://github.com/Holo-Host/holo-nixpkgs/pull/1296/files#diff-1eb3dc60c0623cf690025ad71ae4572089508b4680d49f527bc61ac5249c575bR36) might need more polishing. Do really both of those services need `configure-holochain.service`?

2022-07-20 11:16 UTC, peeech commented
- I wouldn't include changes in `profiles/logical/holo/match-server/default.nix` and `profiles/logical/hpos/default.nix` in this PR. Once merged match-server and Holoports would try to communicate with `holoBusinessServicesServer` which is not deployed, yet. To me it looks like a correct order would be: finish and merge this PR -> deploy `holoBusinessServicesServer` -> update both profiles in a separate PR -> kill mem-proof-server and delete its profile from holo-nixpkgs

2022-07-20 11:17 UTC, peeech requested changes
See comments in a PR

2022-07-21 11:53 UTC, zeeshan595 commented
@peeech That's all of the comments resolved :)

2022-07-24 06:34 UTC, peeech requested changes
More comments - mostly polishing new service profile

2022-07-24 06:34 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +
```suggestion
```
Those two lines are redundant, because they are already present in [holochain services definition](https://github.com/Holo-Host/holo-nixpkgs/blob/feature/new-registration/modules/services/holochain.nix#L59-L60)

2022-07-24 06:34 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +      locations."/holo-business-services/auth/".proxyPass = "http://${authSocket}:/";
```suggestion
      locations."/holochain-api/".proxyPass = "http://unix:/run/hpos-holochain-api/hpos-holochain-api.sock:/";
```
`holochain-api` needs to be available at http://localhost only for tests. Other two services are not used in NixOs tests, so those two lines are not required

2022-07-24 06:34 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +    email = "przemek.klimek@holo.host";
```suggestion
    email = "acme@holo.host";
```
I am slowly removing my address from acme config - too many email from letsencrypt :-)

2022-07-24 06:34 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +    holo-network = "dummyNet";
This sounds wrong to me, but I am not sure what it is exactly supposed to mean. I can see in git history that this comment was made by Joel - can you check with him?

2022-07-26 10:11 UTC, zeeshan595 commented on profiles/logical/holo/holo-business-services/default.nix
> +  magicLinkSecret = (builtins.readFile /var/lib/holo-business-services/magic-link-secret);
There is a new secret file that is required. This is the magic link api secret. It is used to verify the magic link used by the user is valid and they have been authenticated

2022-07-26 14:51 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +  magicLinkSecret = (builtins.readFile /var/lib/holo-business-services/magic-link-secret);
@zeeshan595 can you add this information (about both files) to a comment at the top of this profile? This will help during deployment. I am trying to create a codebase that is self explanatory, where there would be no action that requires some sort of secret knowledge.

2022-08-11 09:09 UTC, peeech commented on modules/services/hbs-auth.nix
> +    environment = mkOption {
I am seeing that you are passing a name of `holoNetwork` as a value of this option. This option is then passed in form of `environment.NODE_ENV` to a binary. What I think should happen here is that based on the value of `holoNetwork` we should be passing a valid value of NODE_ENV, i.e. "development" for "devNet".

2022-08-11 09:27 UTC, zeeshan595 commented on modules/services/hbs-auth.nix
> +    environment = mkOption {
Yea, that would be preferable but this is mainly used for `sentry` environments. 
We are using sentry to capture any errors and it is useful to know which environment these are coming from.

2022-08-11 09:31 UTC, peeech commented on modules/services/hbs-auth.nix
> +    environment = mkOption {
Ah ok! Then it is definitely all correct.

2022-08-11 09:37 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +#
Actually this profile starts them automatically, I thin this part of a comment is misleading

2022-08-31 09:52 UTC, alastairong requested changes
Please review the entire HBS profile with PJ again to make sure it is up to date with the latest membrane proof configuration.

2022-08-31 09:52 UTC, alastairong commented on profiles/logical/holo/holo-business-services/default.nix
> +    holo-network = "dummyNet";
This needs to be changed to `force-random-agent-key = ( settings.holoNetwork == "devNet" );`

Or just deleted (it doesn't exist in the current develop memproof)

2022-08-31 09:52 UTC, alastairong commented on profiles/logical/holo/holo-business-services/default.nix
> +          bundle_url = "https://holo-host.github.io/joining-code-happ/releases/downloads/0_2_2/joining-code-factory.0_2_2.happ";
New hApp

https://holo-host.github.io/joining-code-happ/releases/downloads/0_3_0/joining-code-factory.0_3_0.happ

2022-08-31 09:52 UTC, alastairong commented on profiles/logical/holo/holo-business-services/default.nix
> +}
Needs a server key path now:

```
 # Need to set this config that is similar to the hpos-config file
  # v2.device_bundle files should exist in this JSON
  systemd.globalEnvironment.HPOS_CONFIG_PATH = "/var/lib/server-key-config.json";
```

2022-08-31 09:52 UTC, alastairong commented on profiles/logical/holo/holo-business-services/default.nix
> +      environment_path = "${holochainWorkingDir}/databases_sqlite3";
environment_path = "${holochainWorkingDir}/db_sqlite3_${holoNetwork.networkName}";

2022-08-31 11:41 UTC, peeech approved these changes

2022-08-31 17:48 UTC, peeech commented on profiles/logical/holo/holo-business-services/default.nix
> +    preStart = "false";
```suggestion
```
According to Joel those two lines should also be removed from profile

2022-08-31 17:50 UTC, peeech approved these changes
Once we figure out why are nightly tests failing this PR is good to go IMHO

2022-09-02 13:13 UTC, merged