self-hosted-happs -> configure-holochain
Holo-Host/holo-nixpkgs pull request #611
Opened 2020-11-19 13:23 UTC by peeech

Fresh start for switching from node version to rust version of the script

2020-11-19 17:05 UTC, Br1ght0ne requested changes

2020-11-19 17:05 UTC, Br1ght0ne commented on overlays/holo-nixpkgs/configure-holochain/default.nix
> +  inherit (rust.packages.nightly) rustPlatform;
This should be left out.

2020-11-19 17:05 UTC, Br1ght0ne commented on overlays/holo-nixpkgs/default.nix
> +  configure-holochain = callPackage ./configure-holochain {
When using `packageName = callPackage ...` form, the top-level export in `configure-holochain/default.nix` should be `rustPlatform.buildRustPackage`, not `{ configure-holochain = ... }`.

2021-01-12 17:06 UTC, peeech commented
Cherry-picked into #657

2021-01-12 17:06 UTC, closed without merging