Merge installer profiles and modules
Holo-Host/holo-nixpkgs pull request #634
Opened 2020-12-08 10:42 UTC by alastairong

2020-12-08 10:49 UTC, alastairong commented on profiles/installers/holoport-plus/default.nix
> +}
```suggestion

  isoImage.makeUsbBootable = true;
}
```

2020-12-08 11:00 UTC, alastairong commented on profiles/physical/hpos/default.nix
> +  hardware.enableRedistributableFirmware = lib.mkForce false;
```suggestion
  hardware.enableRedistributableFirmware = lib.mkForce false; # Needed because hardware-configuration.nix generated on 20.09 install has conflict. Old HoloPorts do not have this conflict as hardware-configuration is still 19.09 version (does not get updated on `nixos-rebuild switch`)
```

2020-12-08 16:20 UTC, alastairong commented
@peeech Tested and confirmed working on both Holoport and Nano :)

2020-12-09 06:16 UTC, peeech requested changes
Small changes requested for sake of documentation

2020-12-09 06:16 UTC, peeech commented on profiles/physical/hpos/default.nix
> +  hardware.enableRedistributableFirmware = lib.mkForce false; # Needed because hardware-configuration.nix generated on 20.09 install has conflict. Old HoloPorts do not have this conflict as hardware-
```suggestion
  # Needed because hardware-configuration.nix generated on 20.09 install has conflict.
  # Old HoloPorts do not have this conflict as hardware-configuration is still 19.09 version
  # and does not get updated on `nixos-rebuild switch`
  hardware.enableRedistributableFirmware = lib.mkForce false;
```
Multiline comment formatted

2020-12-09 06:16 UTC, peeech commented on profiles/installers/holoport-nano/default.nix
> +  in nixpkgs-2009-latest.nix;
This substitution deserves a one line comment why we are doing it

2020-12-09 09:27 UTC, alastairong commented on profiles/installers/holoport-nano/default.nix
> +  in nixpkgs-2009-latest.nix;
I have no idea why we do it. It's something from Yegor's old code and it works

2020-12-09 09:36 UTC, peeech commented on profiles/installers/holoport-nano/default.nix
> +  in nixpkgs-2009-latest.nix;
```suggestion
  # use version of nixpkgs with latest patches
  nix.package = let
    nixpkgs-2009-latest = import (fetchTarball https://github.com/NixOS/nixpkgs/archive/nixos-20.09.tar.gz) {};
  in nixpkgs-2009-latest.nix;
```

2020-12-09 14:10 UTC, peeech approved these changes
excellent 🥇

2020-12-09 14:10 UTC, merged