Update holochain-api endpoint /hosted_happs returns number of source chains
Holo-Host/holo-nixpkgs pull request #655
Opened 2021-01-08 16:56 UTC by zo-el

- [ ] `/hosted_happs` return number of source chains
- [x] Added `hpos-holochain-client` 
- [x] Added tests for `holochain`
- [ ] Added tests for `hpos-holochain-api`

2021-01-18 20:22 UTC, zo-el commented on overlays/holo-nixpkgs/holochain/default.nix
> +      , rev ? "ea026def01d1573d5e0edfb7f4e3e9453f88c43e"
**Note:** This bump is needed because we are now using the `registerDna` updates

2021-01-18 20:22 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-admin-client/hpos-admin-client.py
> -@cli.command(help='Get info on happs currently hosted')
**Note:**  This endpoint was moved to hpos-holochain-api

2021-01-18 20:25 UTC, zo-el commented on profiles/logical/hpos/default.nix
> +  services.holochain = lib.mkDefault {
**Note:** These are set to default so that we can override them in the sandbox setup
cc: @peeech

2021-01-18 23:03 UTC, zo-el commented
Another thought about the `hpos-holochain-api` work is that we can move it to its own repo so that we can run the express tests on a CI
cc: @zippy @peeech.

2021-01-19 10:51 UTC, Br1ght0ne reviewed
Great work @zo-el! I left a few comments.

Remaining things to address:
- how can we run tests that require the sandbox to be disabled only when we're running under sandbox?

2021-01-19 10:51 UTC, Br1ght0ne commented on tests/hpos-holochain-api/default.nix
> +    # machine.wait_for_unit("configure-holochain.service")
`configure-holochain` is a [oneshot systemd service](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=). In its [current configuration](https://github.com/Holo-Host/holo-nixpkgs/blob/2021-01-07/holochain-api/modules/services/configure-holochain.nix#L43-L49), `RemainAfterExit` is not set (to `yes`), meaning that the status of `configure-holochain.service` is never equal to `active`, only `activating` or `deactivating`.
For `machine.wait_for_unit` to work, `RemainAfterExit = "yes"` needs to be set in `services.configure-holochain.serviceConfig`.

2021-01-19 10:51 UTC, Br1ght0ne commented on tests/hpos-holochain-api/default.nix
> +      hpos-config  # TODO: now inside hpos-config package
```suggestion
      hpos-config
```

2021-01-19 10:51 UTC, Br1ght0ne commented on tests/holochain/default.nix
> +      hpos-config # TODO: now inside hpos-config package
```suggestion
      hpos-config
```

2021-01-19 10:54 UTC, Br1ght0ne commented on tests/hpos-holochain-api/default.nix
> +    services.holochain.config.enable = true;
Pretty sure that `enable` is not an option for Holochain's config file. Maybe you meant `services.holochain.enable`, which should be already set to `true` by the profile?

2021-01-19 22:09 UTC, zippy approved these changes

2021-01-19 22:09 UTC, zippy commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      res.sendStatus(500)
Often times there's a way to put a message into the response if there's a 500 error.  Can we do that?  I think it will help us in debugging.

2021-01-19 22:09 UTC, zippy commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        res.sendStatus(501);
ditto re message if possible.

2021-01-19 22:09 UTC, zippy commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        await installHostedDna(happBundleDetails.happ_id, dnas, hostPubKey, serviceloggerPref)
Can we change the function name to `installHostedHapp` to be more accurate?

2021-01-19 22:09 UTC, zippy commented on overlays/holo-nixpkgs/hpos-holochain-api/src/api.js
> +const installHostedDna = async (happId, dna, agentPubKey, serviceloggerPref) => {
I wonder if it's worth adding a UUID parameter here (that can be null) so we can be setting the UUID for hostedHapps at install time.  This might be useful for us in testing?  Maybe we don't do it now until we specify how it would be added to the source configuration file.  Just a thought.

2021-01-19 22:11 UTC, zippy requested changes
Looks very good.  Some changes requested in the comments and some questions.

2021-01-20 00:05 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/api.js
> +  const appWebsocket = await AppWebsocket.connect(`ws://localhost:${HAPP_PORT}`)
Done. Please look at #665.

2021-01-20 00:08 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        await installHostedDna(happBundleDetails.happ_id, dnas, hostPubKey, serviceloggerPref)
The reason I went this way was that we are not installing UI's from the happ bundle.
But I guess installing Hosted Happs currently only includes installing DNA's, so it is appropriate to call it `installingHostedHapp`

Ill make the changes

2021-01-20 00:12 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/api.js
> +const installHostedDna = async (happId, dna, agentPubKey, serviceloggerPref) => {
We choose to use it we would also have to include the UUID in the happ bundle struct the Holo-Hosting-App, because we cannot just add any UUID since every host should be installing with the same UUID

2021-01-20 00:33 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      res.sendStatus(500)
Implemented in PR #665

2021-01-20 00:33 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        res.sendStatus(501);
Implemented in PR #665

2021-01-20 00:40 UTC, zo-el commented on overlays/holo-nixpkgs/configure-holochain/default.nix
> +    rev = "cade6a3c0638a7dac0634298e64ebb5ec6ade70e";
Should I make this change in this PR or should we update it later?

2021-01-20 14:07 UTC, zo-el commented on tests/hpos-holochain-api/default.nix
> +    # machine.wait_for_unit("configure-holochain.service")
Should we add `RemainAfterExit = "yes"`? Because it makes the tests more reliable. 
It's not necessarily crucial right now. We can also keep this in mind if our tests do start failing.

2021-01-20 16:22 UTC, peeech approved these changes
Looks great to me now that all the tests are passing.

2021-01-25 21:34 UTC, peeech approved these changes
👍

2021-01-25 22:30 UTC, zippy approved these changes

2021-01-26 00:59 UTC, merged