treewide: add trycp server
Holo-Host/holo-nixpkgs pull request #669
Opened 2021-01-21 13:00 UTC by alastairong

Runs a trycp-server module at `localhost:9000`.

Nginx listening and passing at `/trycp`

Enable in configuration.nix by adding:

`trycp-server.enable = true;`

2021-01-22 10:26 UTC, Br1ght0ne approved these changes
LGTM, nicely done!

2021-01-26 19:41 UTC, peeech requested changes

2021-01-26 19:41 UTC, peeech commented on profiles/logical/hpos/default.nix
> +          proxyWebsockets = true;
```suggestion
          proxyWebsockets = true; 
          extraConfig = ''
            proxy_send_timeout 1d;
            proxy_read_timeout 1d;
          '';
```
trycp is gonna be working on connections open for a long time. We need these two directives so that connection does not drop.

2021-02-02 19:55 UTC, peeech approved these changes

2021-02-03 18:33 UTC, merged