profiles: add test profile
Holo-Host/holo-nixpkgs pull request #681
Opened 2021-01-28 16:48 UTC by Br1ght0ne

2021-01-28 18:03 UTC, peeech requested changes

2021-01-28 18:03 UTC, peeech commented on tests/hpos-admin-api/default.nix
>      services.hpos-admin-api.enable = true;
I am thinking that this line needs to go to test profile as well. The purpose of the test profile is to be able to start VM that is exactly the same as test environment. So all the `service.<>.enable = true;` and `services.nginx.virtualHosts.localhost.locations.<>.proxyPass` should make it to the test profile as well.

2021-01-29 14:03 UTC, zo-el reviewed
Looks good, I agree with PJ's suggestions. Also, we were going to merge the two tests into one test right? will that be done in a different PR?

2021-01-29 14:23 UTC, Br1ght0ne commented
@zo-el

> we were going to merge the two tests into one test

If you mean removing `holochain` test, it's part of #678.

2021-01-29 15:01 UTC, zo-el commented
> If you mean removing `holochain` test, it's part of #678.

I mean we were going to merge the `hpos-admin-api` and `hpos-holochain-api` tests into one test file right? so that hydra runs the tests faster?

2021-02-01 10:46 UTC, Br1ght0ne commented on tests/hpos-admin-api/default.nix
>      services.hpos-admin-api.enable = true;
Should be resolved in 47a47f4.

2021-02-05 11:55 UTC, peeech approved these changes
Great work!

2021-02-05 11:55 UTC, merged