Envoy integration
Holo-Host/holo-nixpkgs pull request #693
Opened 2021-02-04 18:59 UTC by alastairong

2021-02-04 20:42 UTC, zo-el requested changes
@alastairong In the envoy repo, we already have a build script in nix. Do we need it in two locations?
This is the work I am referencing: https://github.com/Holo-Host/holo-envoy/pull/53

2021-02-04 20:42 UTC, zo-el commented on overlays/holo-nixpkgs/holo-envoy/default.nix
> +mkYarnPackage rec {
I see we have a build script here as well as in the envoy repo. Do we actually need the scripts to be in both places?

2021-02-05 09:05 UTC, alastairong commented on overlays/holo-nixpkgs/holo-envoy/default.nix
> +mkYarnPackage rec {
I think in general we want the script in `holo-nixpkgs` rather than in `holo-envoy` so that it uses the same nixpkgs etc. as hpos. I just updated in `holo-envoy` because I think we wanted it there too for some other reason e.g. development

2021-02-23 14:32 UTC, alastairong commented
Closing - using PR 694

2021-02-23 14:32 UTC, closed without merging