Hha and tools
Holo-Host/holo-nixpkgs pull request #694
Opened 2021-02-04 19:08 UTC by alastairong

Adding HHA and SL
Also adding hpos-holochain-client to CLI for manual hosted-happ installation (until we do auto-install)

2021-02-04 20:35 UTC, zo-el requested changes
I have left a few comments

2021-02-04 20:35 UTC, zo-el commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ hc-state hpos-reset hpos-admin-client hpos-update-cli git hpos-holochain-client ];
We do not need the `hpos-holochain-client`. It is just meant for the test environment.

2021-02-04 20:35 UTC, zo-el commented on profiles/logical/hpos/default.nix
> +          dna_path = builtins.fetchurl {
`dna_path` is also meant to be used only for the dev environment. For the live `hpos` you need to pass dna_url instead.

Just for context, the need for the dna_path was that in the test environment we cannot download a file since the hpos-tests are run in the sandbox.
All we have to do here is comment in the `dna_url` variable and just pass the URL

2021-02-05 09:08 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ hc-state hpos-reset hpos-admin-client hpos-update-cli git hpos-holochain-client ];
well right now we need it to actually trigger installation of hosted happs right? Since `configure-holochain` doesn't do that.

Also, in my experience it's been useful to expose the api clients to the CLI right now for general testing purposes - the `hpos-admin-client` is as well. We can remove in future when we're truly live.

2021-02-05 09:09 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +          dna_path = builtins.fetchurl {
Cool. Will switch that

2021-02-12 09:35 UTC, Br1ght0ne approved these changes

2021-02-12 09:35 UTC, Br1ght0ne commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ hc-state hpos-reset hpos-admin-client hpos-update-cli git hpos-holochain-client ];
```suggestion
  environment.systemPackages = [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli ];
```

2021-02-12 10:45 UTC, alastairong commented
Due to hydra being a bitch today, I'm merging envoy-integration into this story for testing

2021-02-15 15:50 UTC, zo-el commented on modules/services/holochain.nix
>        requires = [ "lair-keystore.service" ];
```suggestion
      requires = [ "lair-keystore.service" "holo-envoy.service" ];
```

2021-02-15 15:50 UTC, zo-el commented on profiles/logical/hpos/default.nix
> +          # dna_path = builtins.fetchurl {
Should we just clean this up? 
We do not need this commented code here

2021-02-15 15:50 UTC, zo-el commented on overlays/holo-nixpkgs/holo-envoy/default.nix
> +mkYarnPackage rec {
I still think we should have these build derivations in only one place. (Preferably in the holo-envoy repo, since if the holo-envoy code build process needs to be updated we can update it in the same repo.)

Mostly if we have it in two places we need to maintain two spaces with the same code, unless we see an advantage for it

2021-02-15 15:58 UTC, alastairong commented on overlays/holo-nixpkgs/holo-envoy/default.nix
> +mkYarnPackage rec {
@peeech Can you guys discuss and let me know what you'd prefer? I don't mind either. We moved it from holo-envoy to holo-nixpkgs repo for some reason. I think it was to ensure it used the correct holochain.

2021-02-19 11:17 UTC, alastairong commented
@peeech @zo-el We are also going to need to update our hpos tests to be reflective of having envoy and lair shim. I was having trouble doing this locally because my tests seem to be flaky...

Will deal with it next week I guess

2021-02-26 09:21 UTC, peeech commented on overlays/holo-nixpkgs/holo-envoy/default.nix
> +mkYarnPackage rec {
Yarn it is

2021-02-26 09:35 UTC, peeech approved these changes
This looks good

2021-02-26 09:36 UTC, peeech approved these changes

2021-02-26 10:48 UTC, marycamacho commented
Using Admin to merge at PJs request.

2021-02-26 10:49 UTC, merged