Add a flashing orange state to highlight holochain connectivity issues
Holo-Host/holo-nixpkgs pull request #747
Opened 2021-03-16 17:13 UTC by alastairong

If LED manager cannot make a proxy-cli call to the proxy server, it will start flashing orange

Not yet tested

2021-03-22 19:36 UTC, timotree3 approved these changes
I approve of the rust changes with a couple of style suggestions. (can't speak for the nix)

2021-03-22 19:36 UTC, timotree3 commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +                }
```suggestion
                output_string.contains("tokio_task_count")
```

2021-03-22 19:36 UTC, timotree3 commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +            Ok(output) =>{
```suggestion
            Ok(output) => { 
```

2021-03-23 03:23 UTC, Br1ght0ne approved these changes
Nix looks good, and thanks @timotree3 for the review! LGTM.

2021-03-24 10:01 UTC, peeech commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochainAllBinariesWithDeps.hpos.kitsune-p2p-proxy ];
My question here is why do we need to add `holochainAllBinariesWithDeps.hpos.kitsune-p2p-proxy ` to system packages on HPOS?

2021-03-24 10:38 UTC, peeech commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        let conn_kitsune_proxy = match Command::new("proxy-cli")
My only concern here is that this code is executed in a loop every 1s. Assuming 2000 holoports out there it adds 2k/s requests on proxy. Same actually applies to zerotier connection check, where `router-gateway.holo.host` receives 2k/s connections just for a status check. I wonder if we should be worried about that?

2021-03-24 10:40 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochainAllBinariesWithDeps.hpos.kitsune-p2p-proxy ];
My understanding was that the Command::new function in the LED manager code basically runs a shell command and therefore the proxy-cli command needed to be available to the shell. I didn't dig into it deeply so I may have misunderstood

2021-03-24 10:41 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        let conn_kitsune_proxy = match Command::new("proxy-cli")
hmmm maybe we reduce the frequency...let me ask

2021-03-24 10:52 UTC, peeech commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochainAllBinariesWithDeps.hpos.kitsune-p2p-proxy ];
oh, ok. What you are talking about is achieved in [this line](https://github.com/Holo-Host/holo-nixpkgs/blob/LED-update/modules/services/hpos-led-manager.nix#L36) where you add `proxy-cli` to the PATH of `hpos-led-manager.service` that wants to execute `proxy-cli`.

What the line under discussion does it [adds a package](https://search.nixos.org/options?channel=20.09&from=0&size=50&sort=relevance&query=environment.systemPackages) (and its executable binaries like `proxy-cli`) to global environment. As a result all the packages listed here are available in ie bash - so that you can call them when you ssh into your machine.

I think it's unnecessary here.

2021-03-24 11:10 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochainAllBinariesWithDeps.hpos.kitsune-p2p-proxy ];
Well Zippy was saying it's a helpful tool for diagnostics anyway, so perhaps we should include it anyway?

2021-03-24 12:45 UTC, peeech commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochainAllBinariesWithDeps.hpos.kitsune-p2p-proxy ];
#753 is my take on that. I think that if we want to use HPOS as a dev machine (which I do all the time) then having holochain bins available for ssh-ed user is a must. In #753 I am adding all holochian bins. `dna-util` will be replaced with `hc` ASAP.

2021-03-24 12:54 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        let conn_kitsune_proxy = match Command::new("proxy-cli")
I will switch this to once every 30 seconds. I won't change the ZT frequency.

2021-03-24 12:57 UTC, peeech commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        let conn_kitsune_proxy = match Command::new("proxy-cli")
This will change frequency of both checks. The other duration `Duration::new(1, 0)` is a timeout for TCP call.

2021-03-24 14:19 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +
@timotree3 Can I get your review on the Rust syntax here? I want is to check proxy connectivity every 30 seconds and everything else every 1 second. In between those 30 seconds, the proxy check should just continue to show the result of the last check.

2021-03-24 14:26 UTC, timotree3 commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        counter = counter + 1;
```suggestion
        if counter == 0 {
            conn_kitsune_proxy = match Command::new("proxy-cli")
                .args(&["--", &args.flag_kitsune])
                .output()
            {   
                Ok(output) => { 
                    let output_string = String::from_utf8(output.stdout)?;
                    output_string.contains("tokio_task_count")
                },
                Err(_) => false,
            };
        };
        
        counter = (counter + 1) % 30;
```

this is how I would do it but your way is fine too

2021-03-24 15:06 UTC, zippy requested changes

2021-03-24 15:06 UTC, zippy commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        counter = (counter + 1) % 30;
This looks like it won't work to me.  This will allways evaluate to 1.

2021-03-24 15:16 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        counter = (counter + 1) % 30;
Did I get the syntax wrong for incrementing?

2021-03-24 18:26 UTC, zippy approved these changes

2021-03-24 18:26 UTC, zippy commented on overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> +        counter = (counter + 1) % 30;
my bad.

2021-03-24 21:43 UTC, merged