overlays/holo-nixpkgs/hpos-holochain-api: Catch up to new holochain
Holo-Host/holo-nixpkgs pull request #756
Opened 2021-03-25 14:24 UTC by timotree3

2021-03-25 20:45 UTC, zo-el requested changes
Just left a few comments and questions

2021-03-25 21:55 UTC, timotree3 commented on overlays/holo-nixpkgs/hpos-holochain-api/tests/index.test.js
> +  const listOfHapps = JSON.parse(listOfHappsResponse.text)
Tests were failing because `body` was `undefined` even though `text` contained a JSON string. It's as though there was some feature of the http library that automatically parsed the response text as json and now it's disabled.

2021-03-26 14:42 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/src/const.js
> +      HHA: getId('holo-hosting-app'),
@zo-el @timotree3 Can you align on the correct name here? I think the new bundle is called `core-app`

2021-03-26 14:50 UTC, timotree3 commented on overlays/holo-nixpkgs/hpos-holochain-api/src/const.js
> +      HHA: getId('holo-hosting-app'),
Not sure. @zo-el?

2021-03-26 15:09 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/const.js
> +      HHA: getId('holo-hosting-app'),
Yes it's called core-app.

2021-03-29 14:02 UTC, timotree3 commented on overlays/holo-nixpkgs/hpos-holochain-api/src/const.js
> +      HHA: getId('holo-hosting-app'),
```suggestion
      HHA: getId('core-app'),
```

2021-03-29 14:11 UTC, zo-el approved these changes
Looks good

2021-03-29 18:55 UTC, peeech approved these changes
Looks good

2021-03-29 19:12 UTC, merged

2021-03-30 14:29 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      resolve(JSON.parse(body.toString()))
@timotree3 
JSON.parse can easily throw, and it's not in a `catch` block, so I'm thinking someone could crash the server by sending a badly formatted json body

2021-03-30 14:29 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +    resolve(JSON.parse(body.toString()))
same thing here

2021-03-30 14:31 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      resolve(JSON.parse(body.toString()))
how come you're using `body` and `req.on` data for a GET request?

2021-03-30 17:30 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      resolve(JSON.parse(body.toString()))
using a body/payload on an HTTP GET request is simply very non standard, I thought it wasn't even allowed, but I looked into it and was wrong, and I'm not one who believes in being super dogmatic anyways, I just was surprised this even worked.
Worth noting that one cannot access this method usefully as a GET request through a browser, because you can't pass the params it calls for as query params or directly in the path

2021-03-30 17:45 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      resolve(JSON.parse(body.toString()))
@timotree3 I wasn't totally sure, so I peeked at the tests and saw I could add one easily: 
here's steps to replicate a crashing request
https://github.com/Holo-Host/holo-nixpkgs/pull/767

2021-03-30 17:46 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      resolve(JSON.parse(body.toString()))
and this wasn't your doing, I can see the JSON.parse was already there, uncaught

2021-03-30 17:46 UTC, Connoropolous commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +      resolve(JSON.parse(body.toString()))
the important thing to remember is that JSON.parse throws an error with a bad input, it doesn't just return `undefined`