Fix tests
Holo-Host/holo-nixpkgs pull request #758
Opened 2021-03-25 18:57 UTC by alastairong

Fixes flakey tests caused by lair needing more time to get ready and api-nginx dependencies. 
Bumps tests for new holochain

2021-03-25 20:56 UTC, Br1ght0ne requested changes
Checks out, except for service configuration nitpicks.

2021-03-25 20:56 UTC, Br1ght0ne commented on modules/services/hpos-admin-api.nix
> +      wantedBy = [ "multi-user.target" "nginx.service" ];
There's no reason `nginx.service` would "want" this to be started. `wantedBy` makes sense only as a guide to when the service should be started (`multi-user.target` effectively means "system is accessible to multiple users == startup finished").

```suggestion
      wantedBy = [ "multi-user.target" ];
```

2021-03-25 20:56 UTC, Br1ght0ne commented on modules/services/hpos-holochain-api.nix
> +      wantedBy = [ "multi-user.target" "nginx.service" ];
```suggestion
```

2021-03-26 09:00 UTC, alastairong commented on modules/services/hpos-holochain-api.nix
> +      wantedBy = [ "multi-user.target" "nginx.service" ];
LOL I misread that as `required = `. Will address

2021-03-26 09:05 UTC, alastairong commented
Ironically, it failed tests. This was because Envoy took 12 seconds to get ready.

I will change from a sleep to a more intelligent wait, since I don't want to add a 15 second forced sleep whenever Envoy restarts

2021-03-26 11:44 UTC, alastairong commented
@Br1ght0ne Can i get a re-review please? 

Updated Envoy service to wait until it has started the server, for a max of 1 minute
Also updated hpos-holochain-api to wait for holochain

The envoy handling is probably overkill normally. It takes ages on hydra but not when running locally.

2021-03-26 11:47 UTC, Br1ght0ne approved these changes
LGTM, thanks @alastairong!

2021-03-26 13:26 UTC, merged