B-04253: holo-auto-pilot
Holo-Host/holo-nixpkgs pull request #837
Opened 2021-05-15 15:54 UTC by zo-el

This should be pointing to PR #836

2021-05-17 15:35 UTC, peeech requested changes

2021-05-17 15:35 UTC, peeech commented on modules/services/holo-auto-pilot.nix
> +      createHome = true;
```suggestion
      createHome = false;
```
`working-directory` in question is already used by `configure-holochain` user

2021-05-17 15:35 UTC, peeech commented on modules/services/holo-auto-pilot.nix
> +      requisite = [ "holochain.service" "hpos-holochain-api.service" "configure-holochain.service" ];
```suggestion
      after = [ "network.target" "configure-holochain.service" ];
      requisite = [ "configure-holochain.service" ];
```
`configure-holochain` already depends on `holochain.service` and `hpos-holochain-api.service`

2021-05-17 15:35 UTC, peeech commented on modules/services/holo-auto-pilot.nix
> +    };
```suggestion
        Type = "oneshot"; 
      };
      
      systemd.timers.holo-auto-pilot = {
        enable = true;
        wantedBy = [ "multi-user.target" ];

        timerConfig = {
          OnUnitActiveSec = "5min"; # run every 5 min
          OnBootSec = "2min"; # first run 2 min after boot
          Unit = "holo-auto-pilot.service";
        };
      };
    };
```

2021-05-17 15:35 UTC, peeech commented on modules/services/holo-auto-pilot.nix
> +    };
Timer will start `holo-auto-pilot.service` every 5 min. Please check the syntax before commiting, editing code in github UI seems very error-prone.

2021-05-17 15:35 UTC, peeech commented on modules/services/holo-auto-pilot.nix
> +
```suggestion
```
config files are built in `preStart` phase of `configure-holochain.service`. Because `holo-auto-pilot.service` depends on `configure-holochain.service` config files are in place by the time `holo-auto-pilot.service` runs, I think.

2021-05-17 15:35 UTC, peeech commented on modules/services/holo-auto-pilot.nix
> +    };
```suggestion
```
Seems like you are only using `package`, `enable` and `working-directory`.

2021-05-18 16:50 UTC, alastairong commented
This works (tested across 2 holoports) and has the intended result of having a single happ_id.

I did notice that sometimes autopilot did not exit on completion (I called it in CLI because it wasn't on a timer). I had to ctrl+c to get back to prompt, but when I checked the logs it had finished.

2021-05-20 14:02 UTC, zo-el commented on modules/services/holo-auto-pilot.nix
> +    };
ok, tks :)

2021-05-20 14:02 UTC, zo-el commented on modules/services/holo-auto-pilot.nix
> +    };
cleaning up :)

2021-06-01 08:22 UTC, alastairong approved these changes

2021-06-01 12:08 UTC, peeech approved these changes
Approving, just one question. Why are we disabling here `systemd-resilience-test`?

2021-06-01 13:46 UTC, merged