Auto pilot enable happ
Holo-Host/holo-nixpkgs pull request #853
Opened 2021-05-27 12:34 UTC by alastairong

2021-06-02 10:51 UTC, peeech requested changes

2021-06-02 10:51 UTC, peeech commented on overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
> +>>>>>>> auto-pilot-05-15
There's a merge conflict artifact here. Which one is correct?

2021-06-02 10:51 UTC, peeech commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = with holochainAllBinariesWithDeps.hpos; [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochain hc kitsune-p2p-proxy hpos-config ];
This adds `hpos-config` to PATH in bash. Is that what we need?

2021-06-02 11:26 UTC, zo-el requested changes

2021-06-02 11:26 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        await enableHapp(happBundleDetails.happ_id)
We should probably enableHapp only after the happ is properly installed(`installHostedHapp` is succesfull). Because currently enabling a happy would eventually update the KV store, but if the happ is not properly installed this can be an issue.

unless we also call deactivate happ on failure to install in the next lines, we should make the zome call to enable after we call `installHostedHapp`

2021-06-02 11:50 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = with holochainAllBinariesWithDeps.hpos; [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochain hc kitsune-p2p-proxy hpos-config ];
Oh I just had it there to check the usage. I can remove it now

2021-06-02 11:55 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        await enableHapp(happBundleDetails.happ_id)
Oh great point. Will update

2021-06-02 11:56 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
> +>>>>>>> auto-pilot-05-15
alpha17

2021-06-02 11:56 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
> +>>>>>>> auto-pilot-05-15
Will update

2021-06-03 08:50 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        await enableHapp(happBundleDetails.happ_id)
@zo-el Please take a look at my change. I want to keep everything self-contained to `hpos-holochain-api` so we don't have to revert changes in configure-holochain / auto-installer down the line.

2021-06-03 08:50 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +  environment.systemPackages = with holochainAllBinariesWithDeps.hpos; [ git hc-state hpos-admin-client hpos-holochain-client hpos-reset hpos-update-cli holochain hc kitsune-p2p-proxy hpos-config ];
Addressed

2021-06-06 18:16 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
> +<<<<<<< HEAD
@alastairong, I think you may have missed this

2021-06-07 07:36 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
> +<<<<<<< HEAD
Yes I think so too!

2021-06-07 17:22 UTC, alastairong commented
@zo-el Addressed issues

2021-06-07 17:29 UTC, zo-el approved these changes
Just one clean up suggestion, else looks good

2021-06-07 17:29 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        if (installed) { await enableHapp(happBundleDetails.happ_id) }
We don't really think this condition here,

2021-06-09 13:30 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        if (installed) { await enableHapp(happBundleDetails.happ_id) }
What do you mean? I thought this is the logic to ensure we only call enableHapp if installHostedHapp succeeds

2021-06-09 13:39 UTC, alastairong commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        if (installed) { await enableHapp(happBundleDetails.happ_id) }
@zo-el Or we could instead get the result of `listInstalledHapps` and call enable happ on each one? It's an idempotent zome call.

2021-06-15 15:55 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        if (installed) { await enableHapp(happBundleDetails.happ_id) }
I mean you do not need to check `if (installed)` because if you `await installHostedHapp` returns an error it will just fall into the try-catch. Else it will continue to enable the happ. 

So` installed` would never be false.

2021-06-15 15:55 UTC, zo-el commented on overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> +        if (installed) { await enableHapp(happBundleDetails.happ_id) }
```suggestion
        await installHostedHapp(happBundleDetails.happ_id, happBundleDetails.happ_bundle.bundle_url, hostPubKey, serviceloggerPref, data.membrane_proofs)
        await enableHapp(happBundleDetails.happ_id)
```

2021-06-16 09:39 UTC, peeech approved these changes
Looks good

2021-06-28 18:33 UTC, merged