Hosted-happs-rc1 patches
Holo-Host/holo-nixpkgs pull request #906
Opened 2021-07-30 13:04 UTC by alastairong

Changelog:
- Updated matching-engine with bug fixes
- Holochain restarter
- Holochain and trycp limitNoFile increase (prep for SQLite)
- match-server profile updates for UID and holoNetwork
- 10GB LMDB database size by default.
-

2021-08-11 12:51 UTC, zo-el requested changes
Left one request and one question

2021-08-11 15:46 UTC, alastairong commented on profiles/logical/holo/match-server/default.nix
> +  systemd.globalEnvironment.DEV_UID_OVERRIDE = "develop";
I agree, but that should be a separate PR?

2021-08-11 15:46 UTC, alastairong commented on profiles/logical/hpos/default.nix
> +    restart-interval = "00/2:30"; # every 2 hours at 30 past
This restart is happening on the pre-release server btw, with no obvious issues so far

2021-08-12 09:28 UTC, zo-el commented on profiles/logical/holo/match-server/default.nix
> +  systemd.globalEnvironment.DEV_UID_OVERRIDE = "develop";
it is pretty straight-forward. Also is a very small thing to be a different PR

2021-08-12 09:28 UTC, zo-el commented on profiles/logical/hpos/default.nix
> +    restart-interval = "00/2:30"; # every 2 hours at 30 past
I mean there is an obvious issue that since it restarts every 2 and a half hours, any Hosted user that is logged in will be disconnected. Which will cause a bad user experience.

2021-08-12 14:50 UTC, zo-el approved these changes
Looks good

2021-08-12 15:46 UTC, merged