[WIP]: joining-code-factor service and profile
Holo-Host/holo-nixpkgs pull request #909
Opened 2021-08-11 16:21 UTC by zo-el

2021-09-08 12:31 UTC, peeech commented on overlays/holo-nixpkgs/holo-registration-service/README.md
> +- MongoDB
Dev only

2021-09-08 12:36 UTC, peeech commented on overlays/holo-nixpkgs/holo-registration-service/src/const.js
> +const CONFIGURE_HC = process.env.NODE_ENV === 'test' ? './tests/config.yaml' : '/var/lib/configure-holochain/config.yaml'
Naybe read it from env var set by Nixos profile? For consistency with other profiles created in holo-nixpkgs.

2021-09-08 12:46 UTC, peeech commented on profiles/logical/holo/holo-registration-server/default.nix
> +      };
indentation

2021-09-08 12:48 UTC, peeech commented on profiles/logical/holo/holo-registration-server/default.nix
> +  };
```suggestion
```

2021-09-08 12:48 UTC, peeech requested changes
A few small requests for change

2021-09-09 14:24 UTC, peeech approved these changes
Great!

2021-09-13 13:22 UTC, JettTech commented on overlays/holo-nixpkgs/holo-registration-service/README.md
> +// REMINDER: Tell zo-el should add more details
> just pointing this out. Do we need me detail here?

2021-09-13 13:44 UTC, JettTech approved these changes
Awesome work! Just found a couple typos, and asked for one small comment. 

:shipit:

2021-09-13 13:44 UTC, JettTech commented on overlays/holo-nixpkgs/holo-registration-service/README.md
> +- `/register-user/` (POST): Validated the registration code and gets back the appropriate joining codes back based on the registration code and role provided.
```suggestion
- `/register-user/` (POST): Validated the registration code and gets back the appropriate joining codes based on the registration code and role provided.
```

2021-09-13 13:44 UTC, JettTech commented on overlays/holo-nixpkgs/holo-registration-service/README.md
> +  - Description: Error returned when something unexpected happens, see the `info` to lear more about this error
```suggestion
  - Description: Error returned when something unexpected happens, see the `info` to learn more about this error
```

2021-09-13 13:44 UTC, JettTech commented on profiles/logical/holo/holo-registration-server/default.nix
> +    membrane-proofs = {
Can we add a temp flag for this too?

2021-09-13 13:58 UTC, zo-el commented on overlays/holo-nixpkgs/holo-registration-service/README.md
> +// REMINDER: Tell zo-el should add more details
Thanks lisa, I had made the updates just needed to remove this reminder.

2021-09-13 14:08 UTC, merged